#pragma once

#define NUM_SHARPIR 6
#define NUM_SONAR 2

#define SHARPIR1_PIN A0
#define SHARPIR2_PIN A1
#define SHARPIR3_PIN A2
#define SHARPIR4_PIN A3
#define SHARPIR5_PIN A4
#define SHARPIR6_PIN A5

#define SONAR1_PIN A6
#define SONAR2_PIN A7

#define STEER_SERVO_PIN D5
#define ESC_PWM_PIN D3
#define PAN_SERVO_PIN D7

#define STEER_SERVO_MIN_PULSE 1000
#define STEER_SERVO_MAX_PULSE 2000

#define ESC_PWM_MIN_PULSE 1000
#define ESC_PWM_MAX_PULSE 2000

#define PAN_SERVO_MIN_PULSE 1000
#define PAN_SERVO_MAX_PULSE 2000

#define TACOMETER_INPUT_PIN D8
#define TACOMETER_DUMMY_PIN D9

#define LED_PIN LED_BUILTIN
